name: Extinguish
version: 2.0
api: 3.15.1
author: Clarence2810
main: clarence2810\extinguish\Main
description: Part of my core (SaioMC Core) 

commands:
  extinguish:
   description: Extinguishing you if you're burning
   aliases:
   - ext
permissions:
  extinguish.command:
    default: op
    description: You can extinguish your self
  extinguish.command.other:
    default: op
    description: You can extinguish other player
