#  _____      _   _                   _     _     
# | ____|_  _| |_(_)_ __   __ _ _   _(_)___| |__  
# |  _| \ \/ / __| | '_ \ / _` | | | | / __| '_ \      Simple plugin by: Clarence2810, Permission: extinguish.command
# | |___ >  <| |_| | | | | (_| | |_| | \__ \ | | |     Plugin Updated: 2:18am 9/7/20 EST
# |_____/_/\_\\__|_|_| |_|\__, |\__,_|_|___/_| |_|     Discord Server: https://discord.gg/Ad2uDSp
#                         |___/                   

############################## GENERAL MESSAGES ##############################

#If player sent extinguish command but dont have permission
no-permission: §cYou dont have permission to run extinguish command!

#If sender dont have permission on extinguishing other player:
other-no-permission: §cYou dont have permission to extinguish other player!

############################## EXTINGUISHING YOUR SELF ##############################

#If player sent extinguish command but not on fire
not-on-fire: §cYou're not even on fire how im gonna extinguish you?

#Success Sending Extinguish Command
extinguished-success: §aYou've been extinguished COOL!

############################## EXTINGUISHING OTHER PLAYER ##############################

#When player is offline or not extist
player-not-found: §c[RADAR] I can't find that player please specify it!

#If player is not on fire | Variable: {player} - who is the player you want to get extinguished
other-not-on-fire: §c{player} is not even on fire dont trick me

#Success extinguished player
#Variable: {sender} - Who run the command to extinguish other player
player-extinguished-success: §aYou've been extinguished by {sender} COOL RIGHT!
#Variable: {player} - who get extinguished
sender-extinguish-success: §aYou extinguished {player} nice!

############################## COOLDOWN SYSTEM ##############################

#If you wanted to have cooldown to run extinguish command | True = theres cooldown and Anything you type = theres no cooldown
command-cooldown: yes
#If you setted command-cooldown in true type a second how long that player can run again the extinguish command
extinguish-cooldown: 10

#When sender is on cooldown | Variable: {remaining} - How long can run again the extinguish
on-cooldown: §cYou are currently at {remaining}seconds(s) cooldown!

#When player is in cooldown this will be sended to sender if the player is specified to get extinguish
#Variable: {remaining} - How long can run again the extinguish
#Variable: {player} - The player specified on sender comman
other-on-cooldown: §c{player} is currently at {remaining}second(s) cooldown!

